In [45]:
# import necessary libraries

import pandas as pd

In [46]:
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [48]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [49]:
df.duplicated().sum()

0

In [50]:
# There are no duplicates records

**DATA CLEANING**

In [51]:
# Need to change the data type of date_added

In [52]:
# Converted the data format from "September 24, 2021" to 2021-09-24 for better data analysis and dropped the data_added column

In [53]:
df['date_added_in_netflix'] = pd.to_datetime(df['date_added'], format='%B %d, %Y', errors='coerce')

In [54]:
df.drop(columns=["date_added"],inplace=True)

In [55]:
df.head(2)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,date_added_in_netflix
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021-09-25
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021-09-24

In [56]:
# Drop the missing values

In [57]:
df.dropna(inplace=True)

In [58]:
df.head(2)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,date_added_in_netflix
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021-09-24
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24

In [59]:
# Dropped the null values

In [60]:
df.isnull().sum()

show_id                  0
type                     0
title                    0
director                 0
cast                     0
country                  0
release_year             0
rating                   0
duration                 0
listed_in                0
description              0
date_added_in_netflix    0
dtype: int64

In [61]:
df.reset_index(drop=True,inplace=True)

In [62]:
df.head(2)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,date_added_in_netflix
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021-09-24
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24

In [63]:
# Resetted the index after dropping the null values

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5328 entries, 0 to 5327
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   show_id                5328 non-null   object
 1   type                   5328 non-null   object
 2   title                  5328 non-null   object
 3   director               5328 non-null   object
 4   cast                   5328 non-null   object
 5   country                5328 non-null   object
 6   release_year           5328 non-null   int64
 7   rating                 5328 non-null   object
 8   duration               5328 non-null   object
 9   listed_in              5328 non-null   object
 10  description            5328 non-null   object
 11  date_added_in_netflix  5328 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 499.6+ KB

In [65]:
df[['duration_int', 'duration_type']] = df['duration'].str.extract(r'(\d+)\s*(min|Season[s]?)')

df['duration_int'] = pd.to_numeric(df['duration_int'])

In [66]:
df.head(2)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,date_added_in_netflix,duration_int,duration_type
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021-09-24,125,min
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24,9,Seasons

In [67]:
# created new columns from duration called 'duration_int' and 'duration_type' for better data analyze
# Sepearated the min and seasons

In [68]:
df.drop(columns=['duration','show_id'],inplace=True)
df.head(2)

,type,title,director,cast,country,release_year,rating,listed_in,description,date_added_in_netflix,duration_int,duration_type
0,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021-09-24,125,min
1,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021,TV-14,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24,9,Seasons

In [69]:
# Dropped the duration and show id  columns (show id droped because it have unique values)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5328 entries, 0 to 5327
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   type                   5328 non-null   object
 1   title                  5328 non-null   object
 2   director               5328 non-null   object
 3   cast                   5328 non-null   object
 4   country                5328 non-null   object
 5   release_year           5328 non-null   int64
 6   rating                 5328 non-null   object
 7   listed_in              5328 non-null   object
 8   description            5328 non-null   object
 9   date_added_in_netflix  5328 non-null   datetime64[ns]
 10  duration_int           5328 non-null   int64
 11  duration_type          5328 non-null   object
dtypes: datetime64[ns](1), int64(2), object(9)
memory usage: 499.6+ KB

In [71]:
df.head()

,type,title,director,cast,country,release_year,rating,listed_in,description,date_added_in_netflix,duration_int,duration_type
0,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021-09-24,125,min
1,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021,TV-14,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,2021-09-24,9,Seasons
2,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021,PG-13,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021-09-24,104,min
3,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021,TV-MA,"Dramas, International Movies",After most of her family is murdered in a terr...,2021-09-23,127,min
4,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,1998,TV-14,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...,2021-09-21,166,min